server:
  port: 8002

spring:
  application:
    name: cloud-payment-service # 服务名称

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud2020?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123456

eureka:
  client:
    register-with-eureka: true #表示向注册中心注册自己 默认为true
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
#      defaultZone: http://localhost:7001/eureka # 入驻地址 单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka # 入驻地址 集群版
  instance:
    instance-id: payment-2号服务   # 修改在Eureka上显示的服务名称
    prefer-ip-address: true       # Eureka上的服务访问路径可以显示IP地址

info:
  app.name: 我是服务端2号!
  company.name: www.baidu.com

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.huju.springcloud.entities  # 所有entity别名所在包